CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    address VARCHAR(128) NOT NULL
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    cost INT NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    CONSTRAINT fk_orders_users FOREIGN KEY (customer_id) REFERENCES users(id)
);

CREATE TABLE orders_items (
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    amount INT NOT NULL,
    CONSTRAINT fk_orders_items_orders FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_orders_items_items FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT pk_orders_items PRIMARY KEY (order_id, item_id)
);